#!/bin/bash

DOWNLOAD_URL+=${RELEASE_PACKAGE}
DOWNLOAD_URL+="_"
DOWNLOAD_URL+=${RELEASE_VERSION}
DOWNLOAD_URL+="_"

DOWNLOAD_URL+=${TARGETARCH}

DOWNLOAD_URL+=".deb/download.deb"

echo "Downloading from ${DOWNLOAD_URL}"

if [[ ${DOWNLOAD_URL} == *"amazonaws"* ]]; then
    echo "Downloading package from Amazon bucket - ${DOWNLOAD_URL}"
    wget --quiet ${DOWNLOAD_URL} -O /tmp/gitlab.deb
else
    echo "Downloading package as artifact - ${DOWNLOAD_URL}"
    # If we are fetching the package which is available as an artifact, we need
    # to authenticate to access it. Hence, we pass PRIVATE-TOKEN header.
    wget --quiet --header "PRIVATE-TOKEN: ${TRIGGER_PRIVATE_TOKEN}" ${DOWNLOAD_URL} -O /tmp/gitlab.deb
fi

exit 0

results=$?
if [ ${results} -ne 0 ]; then
    >&2 echo "There was an error downloading ${DOWNLOAD_URL}. Please check the output for more information"
    exit ${results}
fi
